meta_product_name: "egg•man"
meta_title: "egg•man | designer & developer"
meta_description: "UX/UI Designer • Frontend Developer • Storyteller • Vasco Oliveira © 2021"
meta_image: "cover.png" # should exist in `app/assets/images/`
